### ISSUE TITLE
Ass AccSyncState has no issues tab I'll write here

### ISSUE THREAD

**Issue by Coppersocket** [Madevil/KK_MovUrAcc#1]
The current iteration of ASS interferes with the Clothing State Menu, or more directly- Jetpack seems to interferes with it. While having the newest version installed, the "All accs On" and "All accs Off" buttons do not work.

**Comment by Madevil** [comment]
That's part of designed behavior in current version
When "Force Preview" been enabled, all accs on/off would be blocked
